services:
  rustdesk-client-generator:
    # use bryangerlach/rdgen:latest for the latest build
    #build: .
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "5918a49626b84af0b150edb15a88c1ef54d85844443ed677e3a3540fc4413f5a140eaf37c4eed4cba0040bedcd1e8a1a04a6"
      GHUSER: "jbdelay"
      GHBEARER: ${rustdesk-client-generator}
      GENURL: ${GENURL}
      ZIP_PASSWORD: ${ZIP_PASSWORD}
      GHBRANCH: "master"
      PROTOCOL: "https"
      REPONAME: "rustdesk-client-generator"
      SH_SECRET: "delayservices"
      DEBUG: "True"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
    volumes:
      - ./exe:/opt/rdgen/exe
      - ./png:/opt/rdgen/png
      - ./temp_zips:/opt/rdgen/temp_zips
